### ISSUE TITLE
Potential Downsides?

### ISSUE THREAD

**Issue by sclausen** [SDesya74/bevy_oneshot#1]
I would like to ask, why you call your implementation 'naive'.  Are there any downsides to bevys official [one shot example](/bevyengine/bevy/blob/main/examples/ecs/one_shot_systems.rs)? 

Working with your library let me think "wow nice!" while reading the one_shot_systems example from bevy let me think "why though?"

**Comment by SDesya74** [comment]
Hi, thanks for the feedback, it's nice to hear that you like using this library!

I called the implementation naive because it initializes the system (`system.initialize(world)`) on every call. Because of this, as far as I understand, there can be some performance decrease, but I didn't notice anything terrible.

**Comment by sclausen** [comment]
Thanks for the clarification! For my current project I'm only using this for some user interactions, so that's a negligible issue in that specific case.
